Dev
OlegVankov/fantastic-engine pull request #1
Opened 2024-01-09 20:15 UTC by OlegVankov

2024-01-19 07:10 UTC, edylcrm requested changes

2024-01-19 07:10 UTC, edylcrm commented on internal/handler/accrual/accrual.go
> +		<-time.After(time.Second * time.Duration(5))
[BLOCKER] здесь будет утечка памяти. Лучше использовать time.Ticker и написать как-то так:
```
	t := time.NewTicker(time.Second * time.Duration(5))
	defer t.Stop()

	for {
		select {
		case <-t.C:
			// logic
		}
	}
```
https://github.com/eclipse/paho.mqtt.golang/issues/518

2024-01-19 07:10 UTC, edylcrm commented on internal/handler/handler.go
> +	user, err := h.Repository.GetBalance(context.Background(), username)
[BLOCKER] context нужно брать из Request. Если по какой-то причине клиент отклонит запрос, контекст завершится и запрос в БД выполняться не будет.

2024-01-19 16:13 UTC, OlegVankov commented on internal/handler/handler.go
> +	user, err := h.Repository.GetBalance(context.Background(), username)
fix в коммите 56800debe1f6b962773e8735a4ea31ae1aa00bd7

2024-01-19 16:14 UTC, OlegVankov commented on internal/handler/accrual/accrual.go
> +		<-time.After(time.Second * time.Duration(5))
добавил функцию sleep
коммит 60838f1baff354245d7d89f97c6a69c409f39fe7

2024-01-20 05:06 UTC, edylcrm requested changes

2024-01-20 05:06 UTC, edylcrm commented on internal/handler/accrual/accrual.go
> +	select {
[BLOCKER] Здесь так же стоит добавить defer timer.Stop(). Чтобы после завершения выполнения функции, все ресурсы timer освободились.

2024-01-20 05:06 UTC, edylcrm commented on internal/handler/accrual/accrual.go
> +		if err := sleep(ctx, time.Duration(5)*time.Second); err != nil {
[LINT] выглядит чуть-чуть не красиво. Можно оставить как есть, но обычно так не пишут. Если не хочешь видеть `select` не обязательно делать для этого отдельную функцию. Можно просто написать:
```
func SendAccrual() {
	ticker := time.NewTicker(time.Duration(5)*time.Second)
	defer ticker.Stop()

	for _ = range ticker.C {
		// do something
	}
}
```

2024-01-20 05:06 UTC, edylcrm commented on internal/handler/handler.go
> +	tkn, _ := util.CreateToken(user.Login, user.ID)
[LINT] если CreateToken вернет ошибку, то лучше ее обработать и вернуть пользователю ошибку

2024-01-20 05:06 UTC, edylcrm commented on internal/util/hash.go
> +package util
[INFO] я бы все таки не создавал отдельный пакет util и в нем реализовывал весь общий функционал для lun, jwt, hash. Со временем в этот пакет так же добавляют много все, работу со строками, map, slice и т.д. В какой-то момент пакет сильно разрастается и по всему проекту встречается util.SomeF(). Лучше когда есть отдельный пакет для lum, jwt, hash и т.д.
Но опять же это очень спортный момент.

2024-01-23 16:11 UTC, OlegVankov commented on internal/handler/accrual/accrual.go
> +	select {
удалил функцию
коммит 2f5f087b989b6516f5f6bf5606432301075a07f8

2024-01-23 16:12 UTC, OlegVankov commented on internal/handler/accrual/accrual.go
> +		if err := sleep(ctx, time.Duration(5)*time.Second); err != nil {
переписал цикл с использованием ticker
коммит 2f5f087b989b6516f5f6bf5606432301075a07f8

2024-01-23 16:12 UTC, OlegVankov commented on internal/handler/handler.go
> +	tkn, _ := util.CreateToken(user.Login, user.ID)
обработал ошибку
коммит 2f5f087b989b6516f5f6bf5606432301075a07f8

2024-01-23 16:13 UTC, OlegVankov commented on internal/util/hash.go
> +package util
сделал рефакторинг, перенес файлы по пакетам
коммит 2f5f087b989b6516f5f6bf5606432301075a07f8

2024-01-31 15:27 UTC, edylcrm approved these changes

2024-02-05 13:50 UTC, merged